[package]
name = "modexp"
version = "0.1"
lean_version = "master"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "bf58bf4451f26b88c776586865e6840cd1495f64"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "89cd6ccab627ce049275a147ff6efac0d014243d"}
