[package]
name = "modexp"
version = "0.1"
lean_version = "3.3.0"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "bf58bf4451f26b88c776586865e6840cd1495f64"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "24f6b44e188479db85216d88b662ac942c8a5fc2"}
