[package]
name = "modexp"
version = "0.1"
lean_version = "master"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5ad8020f67eb13896a41cc7691d072c9331b1f76"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "3872e28b137640c73b4c0bb86093df807e08a406"}
